// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Butacas
{
    public int ID_butaca { get; set; }

    public int? ID_sala { get; set; }

    public int? Fila { get; set; }

    public int? Numero { get; set; }

    public int? ID_tipo_butaca { get; set; }

    public int? ID_estado { get; set; }

    public virtual ICollection<Entradas> Entradas { get; set; } = new List<Entradas>();

    public virtual Estado_butacas ID_estadoNavigation { get; set; }

    public virtual Salas ID_salaNavigation { get; set; }

    public virtual Tipo_butacas ID_tipo_butacaNavigation { get; set; }
}