// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace web_api_cine.Models;

public partial class cine_dbContext : DbContext
{
    public cine_dbContext(DbContextOptions<cine_dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Barrios> Barrios { get; set; }

    public virtual DbSet<Butacas> Butacas { get; set; }

    public virtual DbSet<Cines> Cines { get; set; }

    public virtual DbSet<Clasificaciones> Clasificaciones { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<Confiterias> Confiterias { get; set; }

    public virtual DbSet<Detalle_promociones> Detalle_promociones { get; set; }

    public virtual DbSet<Detalle_retiro_confiterias> Detalle_retiro_confiterias { get; set; }

    public virtual DbSet<Detalles_facturas> Detalles_facturas { get; set; }

    public virtual DbSet<Entradas> Entradas { get; set; }

    public virtual DbSet<Estado_butacas> Estado_butacas { get; set; }

    public virtual DbSet<Facturas> Facturas { get; set; }

    public virtual DbSet<Funciones> Funciones { get; set; }

    public virtual DbSet<Generos> Generos { get; set; }

    public virtual DbSet<Idiomas> Idiomas { get; set; }

    public virtual DbSet<Inventarios> Inventarios { get; set; }

    public virtual DbSet<Localidades> Localidades { get; set; }

    public virtual DbSet<Metodo_pagos> Metodo_pagos { get; set; }

    public virtual DbSet<Orden_retiro_confiterias> Orden_retiro_confiterias { get; set; }

    public virtual DbSet<Paises> Paises { get; set; }

    public virtual DbSet<Peliculas> Peliculas { get; set; }

    public virtual DbSet<Productos> Productos { get; set; }

    public virtual DbSet<Promocion_productos> Promocion_productos { get; set; }

    public virtual DbSet<Promociones> Promociones { get; set; }

    public virtual DbSet<Proveedores> Proveedores { get; set; }

    public virtual DbSet<Provincias> Provincias { get; set; }

    public virtual DbSet<Reseñas> Reseñas { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Salas> Salas { get; set; }

    public virtual DbSet<Tipo_Canales> Tipo_Canales { get; set; }

    public virtual DbSet<Tipo_Clientes> Tipo_Clientes { get; set; }

    public virtual DbSet<Tipo_Salas> Tipo_Salas { get; set; }

    public virtual DbSet<Tipo_butacas> Tipo_butacas { get; set; }

    public virtual DbSet<Tipo_trabajadores> Tipo_trabajadores { get; set; }

    public virtual DbSet<Trabajadores> Trabajadores { get; set; }

    public virtual DbSet<Trailers> Trailers { get; set; }

    public virtual DbSet<Usuario_Sistemas> Usuario_Sistemas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Barrios>(entity =>
        {
            entity.HasKey(e => e.ID_barrio).HasName("pk_barrios");

            entity.Property(e => e.Barrio)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Butacas>(entity =>
        {
            entity.HasKey(e => e.ID_butaca).HasName("pk_butacas");

            entity.HasOne(d => d.ID_estadoNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.ID_estado)
                .HasConstraintName("fk_estado_butacas_but");

            entity.HasOne(d => d.ID_salaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.ID_sala)
                .HasConstraintName("fk_salas_but");

            entity.HasOne(d => d.ID_tipo_butacaNavigation).WithMany(p => p.Butacas)
                .HasForeignKey(d => d.ID_tipo_butaca)
                .HasConstraintName("fk_tipo_butaca_but");
        });

        modelBuilder.Entity<Cines>(entity =>
        {
            entity.HasKey(e => e.ID_cine).HasName("pk_Cines");

            entity.Property(e => e.Direccion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_localidadNavigation).WithMany(p => p.Cines)
                .HasForeignKey(d => d.ID_localidad)
                .HasConstraintName("fk_Localidades_Cines");
        });

        modelBuilder.Entity<Clasificaciones>(entity =>
        {
            entity.HasKey(e => e.ID_clasificacion).HasName("pk_Clasificaciones");

            entity.Property(e => e.Clasificacion)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Clientes>(entity =>
        {
            entity.HasKey(e => e.ID_cliente).HasName("pk_clientes");

            entity.Property(e => e.Apellido)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Direccion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.E_mail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("E-mail");
            entity.Property(e => e.Fecha_nacimiento).HasColumnType("datetime");
            entity.Property(e => e.Nombre)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_barrioNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.ID_barrio)
                .HasConstraintName("fk_barrios_Cli");

            entity.HasOne(d => d.ID_tipo_clienteNavigation).WithMany(p => p.Clientes)
                .HasForeignKey(d => d.ID_tipo_cliente)
                .HasConstraintName("fk_tipo_cliente_Cli");
        });

        modelBuilder.Entity<Confiterias>(entity =>
        {
            entity.HasKey(e => e.ID_confiteria).HasName("pk_Confiterias");

            entity.HasOne(d => d.ID_CineNavigation).WithMany(p => p.Confiterias)
                .HasForeignKey(d => d.ID_Cine)
                .HasConstraintName("fk_Cines_Conf");

            entity.HasOne(d => d.ID_trabajadorNavigation).WithMany(p => p.Confiterias)
                .HasForeignKey(d => d.ID_trabajador)
                .HasConstraintName("fk_Trabajadores_Conf");
        });

        modelBuilder.Entity<Detalle_promociones>(entity =>
        {
            entity.HasKey(e => e.ID_detalle_promocion);

            entity.Property(e => e.Condiciones)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_funcionNavigation).WithMany(p => p.Detalle_promociones)
                .HasForeignKey(d => d.ID_funcion)
                .HasConstraintName("FK_Funciones_Det_Prom");

            entity.HasOne(d => d.ID_promocionNavigation).WithMany(p => p.Detalle_promociones)
                .HasForeignKey(d => d.ID_promocion)
                .HasConstraintName("FK_Promociones_Det_Prom");
        });

        modelBuilder.Entity<Detalle_retiro_confiterias>(entity =>
        {
            entity.HasKey(e => e.ID_detalle_retiro_conf).HasName("pk_Detalles_retiro_confiteria");

            entity.Property(e => e.Precio_unitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_orden_retiro_confiteriaNavigation).WithMany(p => p.Detalle_retiro_confiterias)
                .HasForeignKey(d => d.ID_orden_retiro_confiteria)
                .HasConstraintName("fk_Orden_retiro_confiterias_Det_Ret_Conf");

            entity.HasOne(d => d.ID_productoNavigation).WithMany(p => p.Detalle_retiro_confiterias)
                .HasForeignKey(d => d.ID_producto)
                .HasConstraintName("fk_Productos_Det_Ret_Conf");
        });

        modelBuilder.Entity<Detalles_facturas>(entity =>
        {
            entity.HasKey(e => e.ID_detalle_factura);

            entity.Property(e => e.Precio_unitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_entradaNavigation).WithMany(p => p.Detalles_facturas)
                .HasForeignKey(d => d.ID_entrada)
                .HasConstraintName("FK_Entradas_Det_Fact");

            entity.HasOne(d => d.ID_facturaNavigation).WithMany(p => p.Detalles_facturas)
                .HasForeignKey(d => d.ID_factura)
                .HasConstraintName("FK_Facturas_Det_Fact");
        });

        modelBuilder.Entity<Entradas>(entity =>
        {
            entity.HasKey(e => e.ID_entrada);

            entity.Property(e => e.Precio_unitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.ID_butacaNavigation).WithMany(p => p.Entradas)
                .HasForeignKey(d => d.ID_butaca)
                .HasConstraintName("FK_Butacas_Entr");

            entity.HasOne(d => d.ID_funcionNavigation).WithMany(p => p.Entradas)
                .HasForeignKey(d => d.ID_funcion)
                .HasConstraintName("FK_Funciones_Entr");
        });

        modelBuilder.Entity<Estado_butacas>(entity =>
        {
            entity.HasKey(e => e.ID_estado).HasName("pk_estados");

            entity.Property(e => e.Estado)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Facturas>(entity =>
        {
            entity.HasKey(e => e.ID_factura);

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.ID_canalNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ID_canal)
                .HasConstraintName("FK_Tipo_Canales_Fact");

            entity.HasOne(d => d.ID_clienteNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ID_cliente)
                .HasConstraintName("FK_Clientes_Fact");

            entity.HasOne(d => d.ID_metodo_pagoNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ID_metodo_pago)
                .HasConstraintName("FK_Metodo_pagos_Fact");

            entity.HasOne(d => d.ID_trabajadorNavigation).WithMany(p => p.Facturas)
                .HasForeignKey(d => d.ID_trabajador)
                .HasConstraintName("FK_Trabajadores_Fact");
        });

        modelBuilder.Entity<Funciones>(entity =>
        {
            entity.HasKey(e => e.ID_funcion).HasName("pk_funciones");

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.ID_idiomaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.ID_idioma)
                .HasConstraintName("fk_Idiomas_Func");

            entity.HasOne(d => d.ID_peliculaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.ID_pelicula)
                .HasConstraintName("fk_peliculas_Func");

            entity.HasOne(d => d.ID_salaNavigation).WithMany(p => p.Funciones)
                .HasForeignKey(d => d.ID_sala)
                .HasConstraintName("fk_salas_Func");
        });

        modelBuilder.Entity<Generos>(entity =>
        {
            entity.HasKey(e => e.ID_genero).HasName("pk_Generos");

            entity.Property(e => e.Genero)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Idiomas>(entity =>
        {
            entity.HasKey(e => e.ID_idioma).HasName("pk_Idiomas");

            entity.Property(e => e.Idioma)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Inventarios>(entity =>
        {
            entity.HasKey(e => e.ID_inventario).HasName("pk_Inventarios");

            entity.Property(e => e.Fecha_actualizacion).HasColumnType("datetime");

            entity.HasOne(d => d.ID_cineNavigation).WithMany(p => p.Inventarios)
                .HasForeignKey(d => d.ID_cine)
                .HasConstraintName("fk_Cines_inv");

            entity.HasOne(d => d.ID_productoNavigation).WithMany(p => p.Inventarios)
                .HasForeignKey(d => d.ID_producto)
                .HasConstraintName("fk_Productos_inv");
        });

        modelBuilder.Entity<Localidades>(entity =>
        {
            entity.HasKey(e => e.ID_localidad).HasName("pk_Localidades");

            entity.Property(e => e.Localidad)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_provinciaNavigation).WithMany(p => p.Localidades)
                .HasForeignKey(d => d.ID_provincia)
                .HasConstraintName("fk_Provincias_Loc");
        });

        modelBuilder.Entity<Metodo_pagos>(entity =>
        {
            entity.HasKey(e => e.ID_metodo_pago);

            entity.Property(e => e.Metodo_pago)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Orden_retiro_confiterias>(entity =>
        {
            entity.HasKey(e => e.ID_orden_retiro_confiteria).HasName("pk_Orden_retiro_confiterias");

            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.ID_clienteNavigation).WithMany(p => p.Orden_retiro_confiterias)
                .HasForeignKey(d => d.ID_cliente)
                .HasConstraintName("fk_Clientes");

            entity.HasOne(d => d.ID_confiteriaNavigation).WithMany(p => p.Orden_retiro_confiterias)
                .HasForeignKey(d => d.ID_confiteria)
                .HasConstraintName("fk_Confiterias_Ord_Ret_Conf");

            entity.HasOne(d => d.ID_metodo_pagoNavigation).WithMany(p => p.Orden_retiro_confiterias)
                .HasForeignKey(d => d.ID_metodo_pago)
                .HasConstraintName("fk_Metodo_pagos_Ord_Ret_Conf");

            entity.HasOne(d => d.ID_trabajadorNavigation).WithMany(p => p.Orden_retiro_confiterias)
                .HasForeignKey(d => d.ID_trabajador)
                .HasConstraintName("fk_Trabajadores_Ord_Ret_Conf");
        });

        modelBuilder.Entity<Paises>(entity =>
        {
            entity.HasKey(e => e.ID_pais).HasName("pk_Paises");

            entity.Property(e => e.Pais)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Peliculas>(entity =>
        {
            entity.HasKey(e => e.ID_pelicula).HasName("pk_peliculas");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Titulo)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_clasificacionNavigation).WithMany(p => p.Peliculas)
                .HasForeignKey(d => d.ID_clasificacion)
                .HasConstraintName("fk_clasificaciones_peli");
        });

        modelBuilder.Entity<Productos>(entity =>
        {
            entity.HasKey(e => e.ID_producto).HasName("pk_Productos");

            entity.Property(e => e.Producto)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_proveedorNavigation).WithMany(p => p.Productos)
                .HasForeignKey(d => d.ID_proveedor)
                .HasConstraintName("fk_Proveedores_Prod");
        });

        modelBuilder.Entity<Promocion_productos>(entity =>
        {
            entity.HasKey(e => e.ID_promocion_producto);

            entity.HasOne(d => d.ID_promocionNavigation).WithMany(p => p.Promocion_productos)
                .HasForeignKey(d => d.ID_promocion)
                .HasConstraintName("FK_Promociones_Promo_Prod");
        });

        modelBuilder.Entity<Promociones>(entity =>
        {
            entity.HasKey(e => e.ID_promocion);

            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Fecha_Inicio).HasColumnType("datetime");
            entity.Property(e => e.Fecha_final).HasColumnType("datetime");
            entity.Property(e => e.Procentaje_desc).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<Proveedores>(entity =>
        {
            entity.HasKey(e => e.ID_proveedor).HasName("pk_Proveedores");

            entity.Property(e => e.Direccion)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Provincias>(entity =>
        {
            entity.HasKey(e => e.ID_provincia).HasName("pk_Provincias");

            entity.Property(e => e.Provincia)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_paisNavigation).WithMany(p => p.Provincias)
                .HasForeignKey(d => d.ID_pais)
                .HasConstraintName("fk_Paises_Prov");
        });

        modelBuilder.Entity<Reseñas>(entity =>
        {
            entity.HasKey(e => e.ID_reseña).HasName("pk_reseñas");

            entity.Property(e => e.Comentario)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.ID_clienteNavigation).WithMany(p => p.Reseñas)
                .HasForeignKey(d => d.ID_cliente)
                .HasConstraintName("fk_clientes_Reseñas");

            entity.HasOne(d => d.ID_peliculaNavigation).WithMany(p => p.Reseñas)
                .HasForeignKey(d => d.ID_pelicula)
                .HasConstraintName("fk_peliculas_Reseñas");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.ID_rol);

            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Rol)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Salas>(entity =>
        {
            entity.HasKey(e => e.ID_sala).HasName("pk_salas");

            entity.Property(e => e.Nombre_sala)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_CineNavigation).WithMany(p => p.Salas)
                .HasForeignKey(d => d.ID_Cine)
                .HasConstraintName("fk_Cines_Salas");
        });

        modelBuilder.Entity<Tipo_Canales>(entity =>
        {
            entity.HasKey(e => e.ID_canal);

            entity.Property(e => e.Descripcion)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tipo_Clientes>(entity =>
        {
            entity.HasKey(e => e.ID_tipo_cliente);

            entity.Property(e => e.Tipo_cliente)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tipo_Salas>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.ID_tipo_sala).ValueGeneratedOnAdd();
            entity.Property(e => e.Tipo)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tipo_butacas>(entity =>
        {
            entity.HasKey(e => e.ID_tipo_butaca);

            entity.Property(e => e.Tipo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tipo_trabajadores>(entity =>
        {
            entity.HasKey(e => e.ID_tipo);

            entity.Property(e => e.Tipo)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Trabajadores>(entity =>
        {
            entity.HasKey(e => e.ID_trabajador);

            entity.Property(e => e.Apellido)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.E_mail)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("E-mail");
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_barrioNavigation).WithMany(p => p.Trabajadores)
                .HasForeignKey(d => d.ID_barrio)
                .HasConstraintName("FK_Barrios_Trab");

            entity.HasOne(d => d.ID_tipoNavigation).WithMany(p => p.Trabajadores)
                .HasForeignKey(d => d.ID_tipo)
                .HasConstraintName("FK_Tipo_trabajadores_Trab");
        });

        modelBuilder.Entity<Trailers>(entity =>
        {
            entity.HasKey(e => e.ID_trailer).HasName("pk_trailers");

            entity.Property(e => e.Url_video)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_peliculaNavigation).WithMany(p => p.Trailers)
                .HasForeignKey(d => d.ID_pelicula)
                .HasConstraintName("fk_peliculas_Trailers");
        });

        modelBuilder.Entity<Usuario_Sistemas>(entity =>
        {
            entity.HasKey(e => e.ID_sistema);

            entity.Property(e => e.Contraseña)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Nombre_usuario)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.ID_clienteNavigation).WithMany(p => p.Usuario_Sistemas)
                .HasForeignKey(d => d.ID_cliente)
                .HasConstraintName("FK_Clientes_Us_Sis");

            entity.HasOne(d => d.ID_rolNavigation).WithMany(p => p.Usuario_Sistemas)
                .HasForeignKey(d => d.ID_rol)
                .HasConstraintName("FK_Roles_Us_Sis");

            entity.HasOne(d => d.ID_trabajadorNavigation).WithMany(p => p.Usuario_Sistemas)
                .HasForeignKey(d => d.ID_trabajador)
                .HasConstraintName("FK_Trabajadores_Us_Sis");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}