// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using web_api_cine.Models;

namespace web_api_cine.Models
{
    public partial class cine_dbContext
    {
        private Icine_dbContextProcedures _procedures;

        public virtual Icine_dbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new cine_dbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public Icine_dbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class cine_dbContextProcedures : Icine_dbContextProcedures
    {
        private readonly cine_dbContext _context;

        public cine_dbContextProcedures(cine_dbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<SP_CONSULTAR_FUNCIONES_CINEResult>> SP_CONSULTAR_FUNCIONES_CINEAsync(string titulo, string genero, DateOnly? fechaDesde, DateOnly? fechaHasta, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "titulo",
                    Size = 50,
                    Value = titulo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "genero",
                    Size = 50,
                    Value = genero ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "fechaDesde",
                    Value = fechaDesde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "fechaHasta",
                    Value = fechaHasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "idCine",
                    Value = idCine ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<SP_CONSULTAR_FUNCIONES_CINEResult>("EXEC @returnValue = [dbo].[SP_CONSULTAR_FUNCIONES_CINE] @titulo = @titulo, @genero = @genero, @fechaDesde = @fechaDesde, @fechaHasta = @fechaHasta, @idCine = @idCine", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_CONSULTAR_STOCK_BAJOResult>> SP_CONSULTAR_STOCK_BAJOAsync(string producto, string proveedor, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "producto",
                    Size = 50,
                    Value = producto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "proveedor",
                    Size = 50,
                    Value = proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "idCine",
                    Value = idCine ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<SP_CONSULTAR_STOCK_BAJOResult>("EXEC @returnValue = [dbo].[SP_CONSULTAR_STOCK_BAJO] @producto = @producto, @proveedor = @proveedor, @idCine = @idCine", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_OCUPACION_FUNCIONESResult>> SP_OCUPACION_FUNCIONESAsync(int? idCine, int? idFuncion, DateOnly? fechaDesde, DateOnly? fechaHasta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idCine",
                    Value = idCine ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "idFuncion",
                    Value = idFuncion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "fechaDesde",
                    Value = fechaDesde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "fechaHasta",
                    Value = fechaHasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<SP_OCUPACION_FUNCIONESResult>("EXEC @returnValue = [dbo].[SP_OCUPACION_FUNCIONES] @idCine = @idCine, @idFuncion = @idFuncion, @fechaDesde = @fechaDesde, @fechaHasta = @fechaHasta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_PRODUCTOS_MAS_VENDIDOSResult>> SP_PRODUCTOS_MAS_VENDIDOSAsync(DateOnly? fechaDesde, DateOnly? fechaHasta, string producto, string proveedor, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fechaDesde",
                    Value = fechaDesde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "fechaHasta",
                    Value = fechaHasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "producto",
                    Size = 50,
                    Value = producto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "proveedor",
                    Size = 50,
                    Value = proveedor ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "idCine",
                    Value = idCine ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<SP_PRODUCTOS_MAS_VENDIDOSResult>("EXEC @returnValue = [dbo].[SP_PRODUCTOS_MAS_VENDIDOS] @fechaDesde = @fechaDesde, @fechaHasta = @fechaHasta, @producto = @producto, @proveedor = @proveedor, @idCine = @idCine", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<SP_REPORTE_VENTAS_CINEResult>> SP_REPORTE_VENTAS_CINEAsync(DateOnly? fechaDesde, DateOnly? fechaHasta, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "fechaDesde",
                    Value = fechaDesde ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "fechaHasta",
                    Value = fechaHasta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Date,
                },
                new SqlParameter
                {
                    ParameterName = "idCine",
                    Value = idCine ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryToListAsync<SP_REPORTE_VENTAS_CINEResult>("EXEC @returnValue = [dbo].[SP_REPORTE_VENTAS_CINE] @fechaDesde = @fechaDesde, @fechaHasta = @fechaHasta, @idCine = @idCine", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
