// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Cines
{
    public int ID_cine { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public int? ID_localidad { get; set; }

    public virtual ICollection<Confiterias> Confiterias { get; set; } = new List<Confiterias>();

    public virtual Localidades ID_localidadNavigation { get; set; }

    public virtual ICollection<Inventarios> Inventarios { get; set; } = new List<Inventarios>();

    public virtual ICollection<Salas> Salas { get; set; } = new List<Salas>();
}