// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Clasificaciones
{
    public int ID_clasificacion { get; set; }

    public string Clasificacion { get; set; }

    public virtual ICollection<Peliculas> Peliculas { get; set; } = new List<Peliculas>();
}