// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Clientes
{
    public int ID_cliente { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? ID_barrio { get; set; }

    public string Direccion { get; set; }

    public long? Telefono { get; set; }

    public string E_mail { get; set; }

    public DateTime? Fecha_nacimiento { get; set; }

    public int? ID_tipo_cliente { get; set; }

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Barrios ID_barrioNavigation { get; set; }

    public virtual Tipo_Clientes ID_tipo_clienteNavigation { get; set; }

    public virtual ICollection<Orden_retiro_confiterias> Orden_retiro_confiterias { get; set; } = new List<Orden_retiro_confiterias>();

    public virtual ICollection<Reseñas> Reseñas { get; set; } = new List<Reseñas>();

    public virtual ICollection<Usuario_Sistemas> Usuario_Sistemas { get; set; } = new List<Usuario_Sistemas>();
}