// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Confiterias
{
    public int ID_confiteria { get; set; }

    public int? ID_Cine { get; set; }

    public int? ID_trabajador { get; set; }

    public virtual Cines ID_CineNavigation { get; set; }

    public virtual Trabajadores ID_trabajadorNavigation { get; set; }

    public virtual ICollection<Orden_retiro_confiterias> Orden_retiro_confiterias { get; set; } = new List<Orden_retiro_confiterias>();
}