// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Detalles_facturas
{
    public int ID_detalle_factura { get; set; }

    public int? ID_entrada { get; set; }

    public int? ID_factura { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Precio_unitario { get; set; }

    public virtual Entradas ID_entradaNavigation { get; set; }

    public virtual Facturas ID_facturaNavigation { get; set; }
}