// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Detalle_retiro_confiterias
{
    public int ID_detalle_retiro_conf { get; set; }

    public int? ID_producto { get; set; }

    public int? ID_orden_retiro_confiteria { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Precio_unitario { get; set; }

    public int? ID_promocion { get; set; }

    public virtual Orden_retiro_confiterias ID_orden_retiro_confiteriaNavigation { get; set; }

    public virtual Productos ID_productoNavigation { get; set; }
}