// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Detalle_promociones
{
    public int ID_detalle_promocion { get; set; }

    public int? ID_funcion { get; set; }

    public int? ID_promocion { get; set; }

    public string Condiciones { get; set; }

    public virtual Funciones ID_funcionNavigation { get; set; }

    public virtual Promociones ID_promocionNavigation { get; set; }
}