// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Entradas
{
    public int ID_entrada { get; set; }

    public int? ID_factura { get; set; }

    public decimal? Precio_unitario { get; set; }

    public int? ID_butaca { get; set; }

    public int? ID_funcion { get; set; }

    public virtual ICollection<Detalles_facturas> Detalles_facturas { get; set; } = new List<Detalles_facturas>();

    public virtual Butacas ID_butacaNavigation { get; set; }

    public virtual Funciones ID_funcionNavigation { get; set; }
}