// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Estado_butacas
{
    public int ID_estado { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Butacas> Butacas { get; set; } = new List<Butacas>();
}