// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Facturas
{
    public int ID_factura { get; set; }

    public int? ID_metodo_pago { get; set; }

    public int? ID_canal { get; set; }

    public int? ID_cliente { get; set; }

    public int? ID_trabajador { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<Detalles_facturas> Detalles_facturas { get; set; } = new List<Detalles_facturas>();

    public virtual Tipo_Canales ID_canalNavigation { get; set; }

    public virtual Clientes ID_clienteNavigation { get; set; }

    public virtual Metodo_pagos ID_metodo_pagoNavigation { get; set; }

    public virtual Trabajadores ID_trabajadorNavigation { get; set; }
}