// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Funciones
{
    public int ID_funcion { get; set; }

    public int? ID_sala { get; set; }

    public int? ID_pelicula { get; set; }

    public int? ID_idioma { get; set; }

    public TimeOnly? Horario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<Detalle_promociones> Detalle_promociones { get; set; } = new List<Detalle_promociones>();

    public virtual ICollection<Entradas> Entradas { get; set; } = new List<Entradas>();

    public virtual Idiomas ID_idiomaNavigation { get; set; }

    public virtual Peliculas ID_peliculaNavigation { get; set; }

    public virtual Salas ID_salaNavigation { get; set; }
}