// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Generos
{
    public int ID_genero { get; set; }

    public string Genero { get; set; }
}