// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using web_api_cine.Models;

namespace web_api_cine.Models
{
    public partial interface Icine_dbContextProcedures
    {
        Task<List<SP_CONSULTAR_FUNCIONES_CINEResult>> SP_CONSULTAR_FUNCIONES_CINEAsync(string titulo, string genero, DateOnly? fechaDesde, DateOnly? fechaHasta, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_CONSULTAR_STOCK_BAJOResult>> SP_CONSULTAR_STOCK_BAJOAsync(string producto, string proveedor, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_OCUPACION_FUNCIONESResult>> SP_OCUPACION_FUNCIONESAsync(int? idCine, int? idFuncion, DateOnly? fechaDesde, DateOnly? fechaHasta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_PRODUCTOS_MAS_VENDIDOSResult>> SP_PRODUCTOS_MAS_VENDIDOSAsync(DateOnly? fechaDesde, DateOnly? fechaHasta, string producto, string proveedor, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_REPORTE_VENTAS_CINEResult>> SP_REPORTE_VENTAS_CINEAsync(DateOnly? fechaDesde, DateOnly? fechaHasta, int? idCine, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
