// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Idiomas
{
    public int ID_idioma { get; set; }

    public string Idioma { get; set; }

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();
}