// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Inventarios
{
    public int ID_inventario { get; set; }

    public int? ID_producto { get; set; }

    public int? Stock_actual { get; set; }

    public int? Stock_minimo { get; set; }

    public DateTime? Fecha_actualizacion { get; set; }

    public int? ID_cine { get; set; }

    public virtual Cines ID_cineNavigation { get; set; }

    public virtual Productos ID_productoNavigation { get; set; }
}