// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Localidades
{
    public int ID_localidad { get; set; }

    public string Localidad { get; set; }

    public int? ID_provincia { get; set; }

    public virtual ICollection<Cines> Cines { get; set; } = new List<Cines>();

    public virtual Provincias ID_provinciaNavigation { get; set; }
}