// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Metodo_pagos
{
    public int ID_metodo_pago { get; set; }

    public string Metodo_pago { get; set; }

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual ICollection<Orden_retiro_confiterias> Orden_retiro_confiterias { get; set; } = new List<Orden_retiro_confiterias>();
}