// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Orden_retiro_confiterias
{
    public int ID_orden_retiro_confiteria { get; set; }

    public int? Numero { get; set; }

    public int? ID_confiteria { get; set; }

    public int? ID_cliente { get; set; }

    public int? ID_trabajador { get; set; }

    public int? ID_metodo_pago { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual ICollection<Detalle_retiro_confiterias> Detalle_retiro_confiterias { get; set; } = new List<Detalle_retiro_confiterias>();

    public virtual Clientes ID_clienteNavigation { get; set; }

    public virtual Confiterias ID_confiteriaNavigation { get; set; }

    public virtual Metodo_pagos ID_metodo_pagoNavigation { get; set; }

    public virtual Trabajadores ID_trabajadorNavigation { get; set; }
}