// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Paises
{
    public int ID_pais { get; set; }

    public string Pais { get; set; }

    public virtual ICollection<Provincias> Provincias { get; set; } = new List<Provincias>();
}