// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Peliculas
{
    public int ID_pelicula { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public int? ID_clasificacion { get; set; }

    public int? ID_genero { get; set; }

    public int? Duracion { get; set; }

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();

    public virtual Clasificaciones ID_clasificacionNavigation { get; set; }

    public virtual ICollection<Reseñas> Reseñas { get; set; } = new List<Reseñas>();

    public virtual ICollection<Trailers> Trailers { get; set; } = new List<Trailers>();
}