// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Productos
{
    public int ID_producto { get; set; }

    public string Producto { get; set; }

    public int? ID_proveedor { get; set; }

    public virtual ICollection<Detalle_retiro_confiterias> Detalle_retiro_confiterias { get; set; } = new List<Detalle_retiro_confiterias>();

    public virtual Proveedores ID_proveedorNavigation { get; set; }

    public virtual ICollection<Inventarios> Inventarios { get; set; } = new List<Inventarios>();
}