// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Promocion_productos
{
    public int ID_promocion_producto { get; set; }

    public int? ID_promocion { get; set; }

    public int? ID_producto { get; set; }

    public virtual Promociones ID_promocionNavigation { get; set; }
}