// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Promociones
{
    public int ID_promocion { get; set; }

    public string Descripcion { get; set; }

    public DateTime? Fecha_Inicio { get; set; }

    public DateTime? Fecha_final { get; set; }

    public decimal? Procentaje_desc { get; set; }

    public virtual ICollection<Detalle_promociones> Detalle_promociones { get; set; } = new List<Detalle_promociones>();

    public virtual ICollection<Promocion_productos> Promocion_productos { get; set; } = new List<Promocion_productos>();
}