// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Proveedores
{
    public int ID_proveedor { get; set; }

    public int? Cuit { get; set; }

    public long? Telefono { get; set; }

    public string Direccion { get; set; }

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}