// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Provincias
{
    public int ID_provincia { get; set; }

    public string Provincia { get; set; }

    public int? ID_pais { get; set; }

    public virtual Paises ID_paisNavigation { get; set; }

    public virtual ICollection<Localidades> Localidades { get; set; } = new List<Localidades>();
}