// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Reseñas
{
    public int ID_reseña { get; set; }

    public int? ID_cliente { get; set; }

    public int? ID_pelicula { get; set; }

    public int? Puntuacion { get; set; }

    public string Comentario { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual Clientes ID_clienteNavigation { get; set; }

    public virtual Peliculas ID_peliculaNavigation { get; set; }
}