// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Roles
{
    public int ID_rol { get; set; }

    public string Rol { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Usuario_Sistemas> Usuario_Sistemas { get; set; } = new List<Usuario_Sistemas>();
}