// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Salas
{
    public int ID_sala { get; set; }

    public int? ID_Cine { get; set; }

    public string Nombre_sala { get; set; }

    public int? capacidad { get; set; }

    public int? ID_tipo_sala { get; set; }

    public virtual ICollection<Butacas> Butacas { get; set; } = new List<Butacas>();

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();

    public virtual Cines ID_CineNavigation { get; set; }
}