// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_cine.Models
{
    public partial class SP_CONSULTAR_FUNCIONES_CINEResult
    {
        [StringLength(50)]
        public string Titulo { get; set; }
        [StringLength(50)]
        public string Genero { get; set; }
        [StringLength(50)]
        public string Cine { get; set; }
        [StringLength(50)]
        public string Sala { get; set; }
        public DateTime? Fecha { get; set; }
        public TimeOnly? Horario { get; set; }
        [StringLength(30)]
        public string Idioma { get; set; }
        public int? Duracion { get; set; }
        [StringLength(50)]
        public string Clasificacion { get; set; }
    }
}
