// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_cine.Models
{
    public partial class SP_CONSULTAR_STOCK_BAJOResult
    {
        [StringLength(50)]
        public string Producto { get; set; }
        public int? CUIT_Proveedor { get; set; }
        public int? Stock_actual { get; set; }
        public int? Stock_minimo { get; set; }
        public int? DiasDesdeUltAct { get; set; }
        [StringLength(9)]
        public string EstadoStock { get; set; }
    }
}
