// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_cine.Models
{
    public partial class SP_OCUPACION_FUNCIONESResult
    {
        public int ID_funcion { get; set; }
        [StringLength(50)]
        public string Pelicula { get; set; }
        [StringLength(50)]
        public string Cine { get; set; }
        [StringLength(50)]
        public string Sala { get; set; }
        public DateTime? Fecha { get; set; }
        public TimeOnly? Horario { get; set; }
        public int? CapacidadTotal { get; set; }
        public int? ButacasOcupadas { get; set; }
        [Column("PorcentajeOcupacion", TypeName = "decimal(5,2)")]
        public decimal? PorcentajeOcupacion { get; set; }
    }
}
