// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_cine.Models
{
    public partial class SP_PRODUCTOS_MAS_VENDIDOSResult
    {
        [StringLength(50)]
        public string Producto { get; set; }
        public int? CUIT_Proveedor { get; set; }
        public int? TotalVendido { get; set; }
        [Column("TotalRecaudado", TypeName = "decimal(38,2)")]
        public decimal? TotalRecaudado { get; set; }
        public int? TotalVentas { get; set; }
        public DateTime? PrimeraVenta { get; set; }
        public DateTime? UltimaVenta { get; set; }
    }
}
