// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace web_api_cine.Models
{
    public partial class SP_REPORTE_VENTAS_CINEResult
    {
        [StringLength(50)]
        public string Pelicula { get; set; }
        public int? EntradasVendidas { get; set; }
        [Column("TotalRecaudado", TypeName = "decimal(38,2)")]
        public decimal? TotalRecaudado { get; set; }
        [Column("PrecioPromedio", TypeName = "decimal(38,6)")]
        public decimal? PrecioPromedio { get; set; }
        public DateTime? PrimeraFuncion { get; set; }
        public DateTime? UltimaFuncion { get; set; }
    }
}
