// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Tipo_Clientes
{
    public int ID_tipo_cliente { get; set; }

    public string Tipo_cliente { get; set; }

    public virtual ICollection<Clientes> Clientes { get; set; } = new List<Clientes>();
}