// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Tipo_Canales
{
    public int ID_canal { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();
}