// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Trabajadores
{
    public int ID_trabajador { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string E_mail { get; set; }

    public long? Telefono { get; set; }

    public int? ID_barrio { get; set; }

    public int? ID_tipo { get; set; }

    public string ContraseñaHash { get; set; }

    public virtual ICollection<Confiterias> Confiterias { get; set; } = new List<Confiterias>();

    public virtual ICollection<Facturas> Facturas { get; set; } = new List<Facturas>();

    public virtual Barrios ID_barrioNavigation { get; set; }

    public virtual Tipo_trabajadores ID_tipoNavigation { get; set; }

    public virtual ICollection<Orden_retiro_confiterias> Orden_retiro_confiterias { get; set; } = new List<Orden_retiro_confiterias>();

    public virtual ICollection<Usuario_Sistemas> Usuario_Sistemas { get; set; } = new List<Usuario_Sistemas>();
}