// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Trailers
{
    public int ID_trailer { get; set; }

    public int? ID_pelicula { get; set; }

    public int? Duracion { get; set; }

    public string Url_video { get; set; }

    public virtual Peliculas ID_peliculaNavigation { get; set; }
}