// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_api_cine.Models;

public partial class Usuario_Sistemas
{
    public int ID_sistema { get; set; }

    public string Nombre_usuario { get; set; }

    public string Contraseña { get; set; }

    public int? ID_rol { get; set; }

    public int? ID_trabajador { get; set; }

    public int? ID_cliente { get; set; }

    public virtual Clientes ID_clienteNavigation { get; set; }

    public virtual Roles ID_rolNavigation { get; set; }

    public virtual Trabajadores ID_trabajadorNavigation { get; set; }
}